name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.6
    - name: Install Package Dependencies
      uses: mstksg/get-package@v1
      with:
        apt-get: qtbase5-dev qtbase5-private-dev qtdeclarative5-dev qtpositioning5-dev qtscript5-dev qttools5-dev qtwebengine5-dev
    - name: Build and test with Rake
      run: rake
